TestFinal/TestFinal/ViewModels/GroupClassViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestFinal.Models;

namespace TestFinal.ViewModels
{
    public class GroupClassViewModel
    {
        public int Id { get; set; }
        public String Title { get; set; }
        public String Description { get; set; }
        public String RoomNumber { get; set; }
        public int ReviewId { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual GroupClass GroupClass { get; set; }
        public virtual ApplicationUser User { get; set; }
        public int AverageRating { get; set; }
    }
}

TestFinal/TestFinal/Controllers/GroupClassController.cs
using TestFinal.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestFinal.Models.Repositores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using TestFinal.ViewModels;
using TestFinal.Models.Repositories;
using TestFinal.Data;
using System.IO;

namespace TestFinal.Controllers
{
    public class GroupClassController : Controller
    {
        private readonly IWebHostEnvironment hostingEnvironment;
        private readonly IGroupClassService groupClassService;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IReviewServices reviewServices;
        private readonly MyDbContext context;
        public UserManager<ApplicationUser> UserManager { get; }

        public GroupClassController(IWebHostEnvironment _hostingEnvironment, IGroupClassService _groupClassService,
            RoleManager<IdentityRole> _roleManager,
               UserManager<ApplicationUser> _userManager,MyDbContext _context , IReviewServices _reviewServices)
        {
            hostingEnvironment = _hostingEnvironment;
            groupClassService = _groupClassService;
            roleManager = _roleManager;
            userManager = _userManager;
            context = _context;
            reviewServices = _reviewServices;
        }

        [AllowAnonymous]
        [HttpGet]

        public IActionResult Index()
        {
            var clasa = groupClassService.ListAllGroupClassWith();
            return View("Index", clasa);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult CreateGroupClass()
        {
            CreateGroupClassViewModel model = new CreateGroupClassViewModel { };

            return View("add", model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CreateGroupClass(CreateGroupClassViewModel model)
        {
            if (ModelState.IsValid)
            {

                GroupClass groupClass = new GroupClass
                {
                    Title = model.Title,
                    Id = model.Id,
                    Description = model.Description,
                    RoomNumber = model.RoomNumber
                };

                await groupClassService.AddGroupClassAsync(groupClass);

                return RedirectToAction("Index", "groupClass");
            }

            return View("add", model);
        }
        [HttpGet]
        public ViewResult List(string category)
        {
            IEnumerable<GroupClass> clasa;

            clasa = groupClassService.ListAllGroupClass();

            return View(new GroupClassListViewModel
            {
                GroupClasses = clasa.ToList(),
            });
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteGroupClass(int id)
        {
            var clasa = await groupClassService.GetGroupClassByIdAsync(id);

            await groupClassService.DeleteGroupClassAsync(clasa);

            return RedirectToAction("Index", "groupClass");
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditGroupClass(EditGroupClassViewModel model)
        {
            var clasa = await groupClassService.GetGroupClassByIdAsync(model.Id);

            if (clasa == null)
            {
                ViewBag.ErrorMessage = $"GroupClass with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                clasa.Title = model.Title;
                clasa.Description = model.Description;
                clasa.RoomNumber = model.RoomNumber;

                await groupClassService.UpdateGroupClassAsync(clasa);

                return RedirectToAction("Index", "groupClass");


            }
            return View("Index", model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditGroupClass(int id)
        {
            var clasa = await groupClassService.GetGroupClassByIdAsync(id);

            if (clasa == null)
            {
                ViewBag.ErrorMessage = $"Car option with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = new EditGroupClassViewModel

            {
                Id = clasa.Id,
                Title = clasa.Title,
                Description = clasa.Description,
                RoomNumber = clasa.RoomNumber

            };

            return View("edit", model);
        }

        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
                return NotFound();



            var groupClass = await groupClassService.GetGroupClassByIdAsync(id);

            if (groupClass == null)
                return NotFound();
            

            var review = reviewServices.GetAllGroupClass().Where(r => r.GroupClass.Id == id).ToList();

            var user = await userManager.GetUserAsync(HttpContext.User);

            var groupclassmodel = new GroupClassViewModel()
            {
                Id = groupClass.Id,
                Title = groupClass.Title,
                Description = groupClass.Description,
                RoomNumber = groupClass.RoomNumber,
                Reviews = review,        
                User = user,
            };

            return View(groupclassmodel);
        }


    }
}

TestFinal/TestFinal/Views/GroupClass/Add.cshtml
@{
    //Layout = null;
}

@model TestFinal.ViewModels.CreateGroupClassViewModel

<!DOCTYPE html>

<html>

<body>
    <style>
        /*----------ADD Classes----------*/

        .add-subscriptions img {
            background-position: cover;
        }

        .add-subscriptions-form {
            /*width: fit-content;*/
            box-shadow: 0 0 3px 0 rgba(0,0,0,0.3);
            background: #fff;
            padding: 20px;
            margin: 8% auto 0;
            text-align: center;
        }

            .add-subscriptions-form h1 {
                color: #ff3c00;
                margin-bottom: 30px;
            }

        #add-subscriptions button {
            color: #fff;
            width: 100%;
            padding: 10px;
            border-radius: 20px;
            font-size: 15px;
            margin: 10px 0;
            border: none;
            outline: none;
            cursor: pointer;
        }

        .add-btn {
            background-color: #000000;
        }

        a {
            text-decoration: none;
        }

        .add-subscriptions-form img {
            width: 70px;
            margin-top: -50px;
        }

        body .add-subscriptions-form {
            background-image: url(image/4moving.jpg);
            background-position: center;
        }
    </style>
    <section id="add-subscriptions">
        <div class="add-subscriptions-form">
            <img src="\image\4moving.jpg" />
            <h1>Add New Class</h1>
            <form asp-action="creategroupclass">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class=" form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RoomNumber" class="control-label"></label>
                    <input asp-for="RoomNumber" class="form-control" />
                    <span asp-validation-for="RoomNumber" class="text-danger"></span>
                </div>
                <br />
                <button type="submit" class="add-btn">Add Classes</button>
            </form>
        </div>
        <br />
    </section>
    <br />

</body>
</html>

TestFinal/TestFinal/Views/GroupClass/Details.cshtml
@model TestFinal.ViewModels.GroupClassViewModel
@using System.Net
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> signInManager
@inject IHttpContextAccessor HttpContextAccessor





<!DOCTYPE html>
<html>

<body>
    <div class="content container-fluid" style="display:compact;">
        <div class="container-fluid text-center container-content">
            <h2 class="">

                <br>
                Reviews
            </h2>
        </div>
        <div class="container-fluid text-center container-content">
            <hr>
            <div class="card mb-3">
                <div class="card-body mx-auto">
                    <h5 class="card-title"></h5>
                    <p class="card-text">
                        @if (@Model.Reviews != null)
                        {
                        <p class="tag-section mb-1 "> @Model.Reviews.Count() reviews</p>
                    }
                    else
                    {
                        <p class="tag-section mb-1 ">
                            0 reviews
                        </p>
                    }
                   </p>
                        @foreach (var item in Model.Reviews)
                        {
                            @Html.Partial("_review", item)
                        }
                        @if (@HttpContextAccessor.HttpContext.User.Identity.Name != null)
                        {
                            <hr />
                            <h3>Leave a review</h3>

                            @using (Html.BeginForm(actionName: "AddReviewGroupClass", controllerName: "Review", FormMethod.Post, htmlAttributes: new { onsubmit = "return VerifyRating()" }))
                            {
                                <div class="form-group">

                                    <textarea class="form-control" name="comment" id="txtBookComment" rows="6"></textarea>
                                </div>

                                <div class="form-group">
                                    <div onmouseout="CRateSelected()">
                                        <i class="fa fa-solid fa-star" id="i1" onclick="CRate(1)" onmouseover="CRateOver(1)" onmouseout="CRateOut(1)"></i>
                                        <i class="fa fa-solid fa-star" id="i2" onclick="CRate(2)" onmouseover="CRateOver(2)" onmouseout="CRateOut(2)"></i>
                                        <i class="fa fa-solid fa-star" id="i3" onclick="CRate(3)" onmouseover="CRateOver(3)" onmouseout="CRateOut(3)"></i>
                                        <i class="fa fa-solid fa-star" id="i4" onclick="CRate(4)" onmouseover="CRateOver(4)" onmouseout="CRateOut(4)"></i>
                                        <i class="fa fa-solid fa-star" id="i5" onclick="CRate(5)" onmouseover="CRateOver(5)" onmouseout="CRateOut(5)"></i>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-9">
                                        <input type="number" style="border:solid ; outline:solid" name="rate" id="lblRating" value="0" />
                                        <input type="hidden" style="border:solid ; outline:solid" name="Id" id="lblRating" value="@Model.Id" />
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-success" style="margin-top:10px;">Send Review</button>
                            }

                        }

                    </div>
            </div>

        </div>
    </div>


    <script>
        var $content = $('.menu-content');
        function showContent(type) {
            $content.hide().filter('.' + type).show();
        }
        $('.menu').on('click', '.menu-btn', function (e) {
            showContent(e.currentTarget.hash.slice(1));
            e.preventDefault();
        });
        // show 'about' content only on page load (if you want)
        showContent('about');
    </script>
    <script>
        function myFunction(imgs) {
            var expandImg = document.getElementById("first_image");
            expandImg.src = imgs.src;
            expandImg.parentElement.style.display = "block";
        }
        function ShowProduct() {
            document.getElementById('div1').style.display = "block";
            document.getElementById('div2').style.display = "none";
            document.getElementById('div3').style.display = "none";
            document.getElementById('div4').style.display = "none";
            document.getElementById('btn-1').focus();
        }
        function ShowSpecifications() {
            document.getElementById('div1').style.display = "none";
            document.getElementById('div2').style.display = "block";
            document.getElementById('div3').style.display = "none";
            document.getElementById('div4').style.display = "none";
            document.getElementById('btn-2').focus();
            document.getElementById('btn-1').setAttribute("class", "nav-link  menu-btn btn-info");
        }
        function ShowDescription() {
            document.getElementById('div1').style.display = "none";
            document.getElementById('div2').style.display = "none";
            document.getElementById('div3').style.display = "block";
            document.getElementById('div4').style.display = "none";
            document.getElementById('btn-3').focus();
            document.getElementById('btn-1').setAttribute("class", "nav-link  menu-btn btn-info");
        }
        function ShowReview() {
            document.getElementById('div1').style.display = "none";
            document.getElementById('div2').style.display = "none";
            document.getElementById('div3').style.display = "none";
            document.getElementById('div4').style.display = "block";
            document.getElementById('btn-4').focus();
            document.getElementById('btn-1').setAttribute("class", "nav-link  menu-btn btn-info");

        }
        function CRate(r) {
            $("#Rating").val(r);
            for (var i = 1; i <= r; i++) {
                $("#i" + i).attr('class', 'fa fa-solid fa-stars-sharp');
            }
            // unselect remaining
            for (var i = r + 1; i <= 5; i++) {
                $("#i" + i).attr('class', 'fa fa-solid fa-star');
            }
        }
        function CRateOver(r) {
            for (var i = 1; i <= r; i++) {
                $("#i" + i).attr('class', 'fa fa-solid fa-star-sharp');
            }
        }
        function CRateOut(r) {
            for (var i = 1; i <= r; i++) {
                $("#i" + i).attr('class', 'fa fa-solid fa-star');
            }
        }
        function CRateSelected() {
            var setRating = $("#Rating").val();
            for (var i = 1; i <= setRating; i++) {
                $("#i" + i).attr('class', 'fa fa-solid fa-home');
            }
        }
        function VerifyRating() {
            var rating = $("#lblRating").val();
            if (rating == "0") {
                alert("Please select rating");
                return false;
            }
        }
    </script>
</body>
</html>

TestFinal/TestFinal/Views/GroupClass/Edit.cshtml
@{
    //Layout = null;
}

@model TestFinal.ViewModels.EditGroupClassViewModel

<!DOCTYPE html>

<html>

<body>
    <style>
        /*----------ADD GroupClass----------*/

        .add-groupclasses img {
            background-position: cover;
        }

        .add-groupclasses-form {
            /*width: fit-content;*/
            box-shadow: 0 0 3px 0 rgba(0,0,0,0.3);
            background: #fff;
            padding: 20px;
            margin: 8% auto 0;
            text-align: center;
        }

            .add-groupclasses-form h1 {
                color: #ff3c00;
                margin-bottom: 30px;
            }

        #add-groupclasses button {
            color: #fff;
            width: 100%;
            padding: 10px;
            border-radius: 20px;
            font-size: 15px;
            margin: 10px 0;
            border: none;
            outline: none;
            cursor: pointer;
        }

        .add-btn {
            background-color: #000000;
        }

        a {
            text-decoration: none;
        }

        .add-groupclasses-form img {
            width: 70px;
            margin-top: -50px;
        }

        body .add-groupclasses-form {
            background-image: url(image/4moving.jpg);
            background-position: center;
        }
    </style>
    <section id="add-groupclasses">
        <div class="add-groupclasses-form">
            <img src="\image\4moving.jpg" />
            <h1>Edit Class</h1>
            <form asp-action="editgroupclass">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class=" form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RoomNumber" class="control-label"></label>
                    <input asp-for="RoomNumber" class="form-control" />
                    <span asp-validation-for="RoomNumber" class="text-danger"></span>
                </div>
                <br />
                <button type="submit" class="add-btn">Edit Classes</button>
            </form>
        </div>
        <br />
    </section>
    <br />

</body>
</html>

TestFinal/TestFinal/Views/GroupClass/Index.cshtml
@inject SignInManager<ApplicationUser> signInManager;
@model IEnumerable<GroupClass>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

</head>
<body>
    <style>
        .content-table {
            border-collapse: collapse;
            margin: 25px 0;
            font-size: 0.9em;
            min-width: 400px;
            border-radius: 5px 5px 0 0;
            overflow: hidden;
            box-shadow: 0 0 20px rgba(0, 0, 0.15);
            align-items: center;
            justify-content: center;
        }

            .content-table thead tr {
                background-color: #00ff90;
                color: #ffffff;
                text-align: left;
                font-weight: bold;
            }

            .content-table th, .content-table td {
                padding: 12px 15px;
            }

            .content-table tbody tr {
                border-bottom: 1px solid #fff;
            }

                .content-table tbody tr:nth-of-type(even) {
                    background-color: #f3f3f3;
                }

                .content-table tbody tr:last-of-type {
                    border-bottom: 2px solid #009879;
                }

        .btn-1 {
            width: 150px;
            height: 55px;
            border: none;
            color: #ffffff;
            background-color: #ff0000;
            border-radius: 4px;
            box-shadow: inset 0 0 0 0 #f9e506;
            transition: ease-out 0.3s;
            font-size: 2rem;
            outline: none;
        }

            .btn-1:hover {
                box-shadow: inset 300px 0 0 0 #f9e506;
                cursor: pointer;
                color: rgba(0, 0, 0.15)
            }

        .search_size {
            width: 200px;
            height: 40px;
        }
    </style>

    <h3>Group Class List</h3>


    <table class=" content-table" style="padding-top:10px;">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>RoomNumber</th>
                @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin")) {
                    <th>Action</th>
                }
            </tr>
        </thead>
        @foreach (var groupClass in Model)
        {
    <tr>
        <td>@groupClass.Id</td>
        <td>@groupClass.Title</td>
        <td>@groupClass.Description</td>
        <td>@groupClass.RoomNumber</td>
        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
        {
    <td>

        <a class="btn btn-danger" asp-action="deletegroupclass" asp-controller="groupclass" asp-route-id="@groupClass.Id">
            <i class="fa fa-delete"></i>
            Delete
        </a>

        <a class="btn btn-info" asp-action="editgroupclass" asp-controller="groupclass" asp-route-id="@groupClass.Id">
            <i class="fa fa-envelope"></i>
            Edit
        </a>

       

    </td>          }
                else
                {
    <td>
        <a class="btn btn-info" asp-action="Details" asp-controller="GroupClass" asp-route-id="@groupClass.Id">
            <i class="fa fa-envelope"></i>
            Review
        </a>
    </td>
                }
       
      
    </tr>
        }
    </table>

    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
        <a asp-controller="groupclass" asp-action="creategroupclass">Add New Class Group</a>

    }

    <section id="classes" class="p-5 bg-primary">
        <div class="container">
            <h2 class="text-center text-white">Our Classes</h2>
            <p class="lead text-center text-white mb-5">
                Antrenamentele de group fitness sunt cât se poate de benefice și merită să le încerci.
            </p>
            <div class="row g-4">
                <div class="col-md-6 col-lg-3">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <img src="~/images/My project.jpg" class="rounded-circle mb-3" alt="" />
                            <h3 class="card-title mb-3">Lifting Weights</h3>
                            <p class="card-text">Weight training, also known as resistance or strength training, builds lean, stronger muscles, strengthens your bones and joints, and can help keep your metabolism in a healthy state — meaning you’ll burn more calories even when you’re resting.</p>
                            <a href="#"><i class="fa-brands fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-github"></i></a>
                            <a href="#"><i class="fa fa-youtube"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <img src="~/images/My project1.jpg" class="rounded-circle mb-3" alt="" />
                            <h3 class="card-title mb-3">Cardio</h3>
                            <p class="card-text">Regular cardio exercise can also help you lose weight, get better sleep, and reduce your risk for chronic disease.</p>
                            <a href="#"><i class="fa-brands fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-github"></i></a>
                            <a href="#"><i class="fa fa-youtube"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <img src="~/images/My project2.jpg" class="rounded-circle mb-3" alt="" />
                            <h3 class="card-title mb-3">Yoga</h3>
                            <p class="card-text">Yoga is a great addition to any fitness routine. Unlike your high-intensity interval training (HIIT) workouts or weight-lifting sessions, yoga is often slow, and it focuses more on being mindful and stretching out the body—two things that come with huge benefits. It's totally possible, though, to incorporate strength training into a yoga workout too.</p>
                            <a href="#"><i class="fa-brands fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-github"></i></a>
                            <a href="#"><i class="fa fa-youtube"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <img src="~/images/My project3.jpg" class="rounded-circle mb-3" alt="" />
                            <h3 class="card-title mb-3">TRX</h3>
                            <p class="card-text">Give a man a suspension trainer, and he'll be pumped for a day – show a man the best TRX exercises, and he'll be ripped for life. Or something like that. First invented by a US Navy SEAL using only a jiu-jitsu belt and parachute webbing back in 1997, the TRX pits your bodyweight against gravity to build functional upper body, lower body and core muscle. And trust us, it burns.</p>
                            <a href="#"><i class="fa-brands fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-github"></i></a>
                            <a href="#"><i class="fa fa-youtube"></i></a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>
</body>
</html>